FROM brunobritorj/azdevops-selfhosted:ubuntu2004-0.3.3

ARG DEBIAN_FRONTEND=noninteractive

# Install Ansible
RUN apt install ansible -y

# Install Terraform
RUN curl https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    tee /etc/apt/sources.list.d/hashicorp.list
RUN apt update
RUN apt install terraform -y
